### ISSUE TITLE
eGPU Support

### ISSUE THREAD

**Issue by Crear12** [AsahiLinux/AsahiLinux.github.io#30]
Though it may be too early to ask considering that the dedicated one still lacks support, will there be eGPU support in AsahiLinux?

**Comment by marcan** [comment]
It's too early to tell; we'll find out when Thunderbolt support is implemented.

**Comment by zmarlon** [comment]
Has it been found out by now if egpus would theoretically work? At least I know that there are arm64 drivers from Nvidia.

**Comment by marcan** [comment]
Thunderbolt support is not yet in, so no. There are some ideas but no actual tests can be done yet.

**Comment by icejix** [comment]
yearly check-in! what's going on here? i assume nothing, since no thunderbolt?

**Comment by ElYaiko** [comment]
This would be 🚀 specially with Steam 👀
